import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { authService } from '../services/authService';

export default function ForgotPassword() {
  const [email, setEmail] = useState(''); const [otp, setOtp] = useState(''); const [demoOtp, setDemoOtp] = useState(''); const [seconds, setSeconds] = useState(0); const [cooldown, setCooldown] = useState(0); const [error, setError] = useState(''); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(false); const navigate = useNavigate();
  useEffect(() => { if (!seconds && !cooldown) return undefined; const timer = window.setInterval(() => { setSeconds((current) => Math.max(0, current - 1)); setCooldown((current) => Math.max(0, current - 1)); }, 1000); return () => window.clearInterval(timer); }, [seconds, cooldown]);
  const validEmail = () => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
  const requestOtp = async () => { if (!validEmail()) return setError(email ? 'Please enter a valid email address.' : 'This field is required.'); setLoading(true); setError(''); try { const response = await authService.requestResetOtp(email); setDemoOtp(response.demoOtp || ''); setSeconds(response.expiresInSeconds || 300); setCooldown(30); setStatus('Demo OTP generated successfully. Use the code shown below.'); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to generate a demo OTP.'); } finally { setLoading(false); } };
  const verify = async (event) => { event.preventDefault(); if (!/^\d{6}$/.test(otp)) return setError('Please enter a valid 6-digit OTP.'); setLoading(true); setError(''); try { const response = await authService.verifyResetOtp(email, otp); navigate('/reset-password', { state: { email, resetToken: response.resetToken } }); } catch (verifyError) { setError(verifyError.response?.data?.message || 'Incorrect or expired OTP.'); } finally { setLoading(false); } };
  return <div className="auth-shell single-auth"><main className="auth-card auth-form-card"><div className="auth-heading"><span className="brand-mark">VS</span><div><p className="eyebrow">Account recovery</p><h2>{demoOtp ? 'Verify your DEMO OTP' : 'Forgot password?'}</h2></div></div><p className="form-intro">{demoOtp ? `Code expires in ${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}.` : 'Generate a temporary demonstration code for your account.'}</p>{status && <div className="alert-success" role="status">{status}</div>}{error && <div className="alert-error" role="alert">{error}</div>}{!demoOtp ? <div className="input-group"><label htmlFor="recovery-email">Email address</label><input id="recovery-email" name="email" type="email" value={email} onChange={(event) => { setEmail(event.target.value); setError(''); }} placeholder="you@example.com" /></div> : <><div className="demo-code" role="status"><span>DEMO OTP</span><strong>{demoOtp}</strong><small>Shown for college project demonstration only.</small></div><div className="input-group"><label htmlFor="recovery-otp">6-digit OTP</label><input id="recovery-otp" inputMode="numeric" maxLength="6" value={otp} onChange={(event) => { setOtp(event.target.value.replace(/\D/g, '')); setError(''); }} placeholder="000000" /></div></>}{!demoOtp ? <button className="btn btn-primary bg-ocean-blue full-width" type="button" onClick={requestOtp} disabled={loading}>{loading ? 'Generating...' : 'Generate demo OTP'}</button> : <div className="payment-actions"><button className="btn btn-primary bg-ocean-blue full-width" type="button" onClick={verify} disabled={loading || !seconds}>{loading ? 'Verifying...' : 'Verify OTP'}</button><button className="text-action" type="button" onClick={requestOtp} disabled={loading || cooldown > 0}>{cooldown > 0 ? `Resend in ${cooldown}s` : 'Resend OTP'}</button></div>}<p className="switch-page"><Link to="/signin">Back to sign in</Link></p></main></div>;
}
