import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';

const methods = ['UPI', 'Card', 'Net banking', 'Wallet'];
export default function Payment() {
  const [method, setMethod] = useState('UPI'); const [value, setValue] = useState(''); const [card, setCard] = useState({ name: '', number: '', expiry: '', cvv: '' }); const [error, setError] = useState(''); const [state, setState] = useState('form'); const navigate = useNavigate();
  const submit = (event) => { event.preventDefault(); const validCard = method !== 'Card' || (card.name.trim() && /^\d{16}$/.test(card.number.replace(/\s/g, '')) && /^\d{2}\/\d{2}$/.test(card.expiry) && /^\d{3,4}$/.test(card.cvv)); if ((method === 'UPI' && !/^\S+@\S+$/.test(value)) || (method !== 'UPI' && method !== 'Card' && !value.trim()) || !validCard) return setError(method === 'UPI' ? 'Enter a valid UPI ID, for example name@bank.' : 'Complete the highlighted demo payment details.'); setError(''); setState('processing'); window.setTimeout(() => setState('success'), 900); };
  const simulateFailure = () => { setError('The demo payment was declined. Check the details and try again.'); setState('failure'); };
  if (state === 'success') return <div className="payment-shell"><section className="payment-result success-result"><span className="result-icon">✓</span><p className="eyebrow">Demo payment complete</p><h1>Payment successful</h1><p>This is a simulated checkout for your project demonstration.</p><div className="receipt"><span>Amount paid</span><strong>₹15.00</strong><span>Reference</span><strong>VS-DEMO-2048</strong><span>Method</span><strong>{method}</strong></div><button className="btn btn-primary bg-eco-green full-width" onClick={() => navigate('/home')}>Return to dashboard</button></section></div>;
  if (state === 'failure') return <div className="payment-shell"><section className="payment-result"><span className="result-icon failure-icon">!</span><p className="eyebrow">Payment not completed</p><h1>Try again</h1><p>{error}</p><div className="payment-actions"><button className="btn btn-primary bg-ocean-blue full-width" onClick={() => { setState('form'); setError(''); }}>Retry payment</button><Link to="/home" className="btn btn-secondary full-width">Cancel and return</Link></div></section></div>;
  return <div className="payment-shell"><header className="payment-header"><Link to="/home" className="back-link">← Dashboard</Link><span className="secure-label">🔒 Demo checkout</span></header><main className="payment-layout"><section className="payment-panel"><p className="eyebrow">VeloSync wallet</p><h1>Complete your ride</h1><p className="form-intro">A clear, secure-looking checkout designed for demonstration.</p><div className="summary-row"><span>Ride fare</span><strong>₹15.00</strong></div><div className="summary-row muted-row"><span>Taxes and fees</span><span>Included</span></div><div className="summary-total"><span>Total</span><strong>₹15.00</strong></div></section><section className="payment-panel"><h2>Choose payment method</h2><div className="method-tabs">{methods.map((item) => <button type="button" key={item} className={method === item ? 'selected' : ''} onClick={() => { setMethod(item); setValue(''); setError(''); }}>{item}</button>)}</div><form onSubmit={submit} noValidate>{method === 'Card' ? <div className="card-fields"><label htmlFor="card-name">Cardholder name</label><input id="card-name" value={card.name} onChange={(event) => setCard({ ...card, name: event.target.value })} placeholder="Demo cardholder" autoComplete="off" /><label htmlFor="card-number">Card number</label><input id="card-number" inputMode="numeric" value={card.number} onChange={(event) => setCard({ ...card, number: event.target.value.replace(/[^\d ]/g, '').slice(0, 19) })} placeholder="0000 0000 0000 0000" autoComplete="off" /><div className="card-row"><div><label htmlFor="card-expiry">Expiry</label><input id="card-expiry" value={card.expiry} onChange={(event) => setCard({ ...card, expiry: event.target.value.slice(0, 5) })} placeholder="MM/YY" autoComplete="off" /></div><div><label htmlFor="card-cvv">CVV</label><input id="card-cvv" inputMode="numeric" type="password" value={card.cvv} onChange={(event) => setCard({ ...card, cvv: event.target.value.replace(/\D/g, '').slice(0, 4) })} placeholder="•••" autoComplete="off" /></div></div></div> : <><label htmlFor="payment-value">{method === 'UPI' ? 'UPI ID' : `${method} account`}</label><input id="payment-value" value={value} onChange={(event) => { setValue(event.target.value); setError(''); }} placeholder={method === 'UPI' ? 'name@bank' : 'Demo details only'} aria-invalid={Boolean(error)} /></>}{error && <span className="error-message" role="alert">{error}</span>}<p className="demo-note">No card number, CVV, or payment credential is stored. This flow is demo-only.</p><div className="payment-actions"><button className="btn btn-primary bg-ocean-blue full-width" type="submit" disabled={state === 'processing'}>{state === 'processing' ? 'Processing...' : 'Pay ₹15.00'}</button><button className="text-action" type="button" onClick={simulateFailure}>Simulate failed payment</button></div></form></section></main></div>;
}
