import { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { authService } from '../services/authService';

export default function ResetPassword() {
  const { state } = useLocation(); const navigate = useNavigate(); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async (event) => { event.preventDefault(); if (password.length < 8 || !/\d/.test(password)) return setError('Password must contain at least 8 characters and one number.'); if (password !== confirm) return setError('Passwords do not match.'); if (!state?.email || !state?.resetToken) return setError('Your reset session is missing. Please request a new OTP.'); setLoading(true); setError(''); try { await authService.resetPassword({ email: state.email, resetToken: state.resetToken, password }); navigate('/signin', { state: { message: 'Password reset successfully. You can now sign in.' } }); } catch (resetError) { setError(resetError.response?.data?.message || 'Unable to reset your password.'); } finally { setLoading(false); } };
  return <div className="auth-shell single-auth"><main className="auth-card auth-form-card"><div className="auth-heading"><span className="brand-mark">VS</span><div><p className="eyebrow">Account recovery</p><h2>Set a new password</h2></div></div><p className="form-intro">Resetting access for {state?.email || 'your account'}.</p>{error && <div className="alert-error" role="alert">{error}</div>}<form onSubmit={submit} noValidate><div className="input-group"><label htmlFor="new-password">New password</label><input id="new-password" type="password" value={password} onChange={(event) => { setPassword(event.target.value); setError(''); }} placeholder="At least 8 characters" autoComplete="new-password" /></div><div className="input-group"><label htmlFor="confirm-password">Confirm password</label><input id="confirm-password" type="password" value={confirm} onChange={(event) => { setConfirm(event.target.value); setError(''); }} placeholder="Repeat your password" autoComplete="new-password" /></div><button className="btn btn-primary bg-ocean-blue full-width" type="submit" disabled={loading}>{loading ? 'Resetting...' : 'Reset password'}</button></form><p className="switch-page"><Link to="/signin">Back to sign in</Link></p></main></div>;
}
